version: 0.2

env:
  parameter-store:
    DOCKERHUB_USERNAME: "/dockerhub/username"
    DOCKERHUB_PASSWORD: "/dockerhub/password"
    VITE_USER_API_URL: "/imagebook-client/VITE_USER_API_URL"
    VITE_IMAGE_API_URL: "/imagebook-client/VITE_IMAGE_API_URL"

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  build:
    commands:
      - echo Building the Docker image...
      - docker build --build-arg VITE_USER_API_URL=$VITE_USER_API_URL --build-arg VITE_IMAGE_API_URL=$VITE_IMAGE_API_URL -t egsundqvist/imagebook-client:latest .
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push egsundqvist/imagebook-client:latest
